### PR TITLE
Use all Bluetooth adapters rather than just hci0.

### LINKED ISSUE #58: Use correct hci device in mijia crate
On some devices (e.g. VIM3L Ubuntu), the default Bluetooth adapter is `hci1` rather than `hci0`. However, `mijia` is hardcoded to use `hci0`, so it fails.

The `mijia` crate should automatically detect the correct adapter to use.

### PR DESCRIPTION
**Pull request by qwandor**
This fixes #58 the bug on VIM3L, which for some reason has `hci1` rather than `hci0`.

Is there a better way to do this?

### CODE REVIEW

File: mijia/src/bluetooth.rs [hunk 1]
```diff
@@ -109,19 +109,38 @@ impl BluetoothSession {
...
     }
 
-    /// Power on the bluetooth adapter adapter and start scanning for devices.
+    /// Power on all bluetooth adapters and start scanning for devices.
     pub async fn start_discovery(&self) -> Result<(), eyre::Error> {
-        let adapter = dbus::nonblock::Proxy::new(
+        let bluez_root = dbus::nonblock::Proxy::new(
             "org.bluez",
-            "/org/bluez/hci0",
+            "/",
```
Comment (alsuren) [inline mijia/src/bluetooth.rs:116]: We might be able to  start at "/org/bluez" but I haven't checked.

**Review by alsuren — APPROVED** [review]

File: mijia/src/bluetooth.rs (hunk 1 above)
Comment (qwandor) [reply mijia/src/bluetooth.rs:116]: That appears not to work.
